### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by rafaeln** [gfduszynski/cm-rgb#27]
Hi. Would you consider adding documentation on how to install cm-rgb from the github repo? (Currently you only point out the possibility of installing via `pip`, but I was curious about the new temp monitor feature)

**Comment by gfduszynski** [comment]
Hi, 
I'll add some info as it's pretty easy.

1. Clone repository
2. Enter the directory
3. Run ``pip install . ``

Folder contains ``setup.py`` which is required by pip for install.

This should be sufficient, however since I don't have dev branch; masterer may be sometimes unstable. If you have previously installed ``cm-rgb`` try following:

1. Clone repository
2. Enter the directory
3. Run for example ``./scripts/cm-rgb-monitor --show-temp --temp-source k10temp-pci-00c3/Tdie --print-values --interval=1``

Let me know if this helped you.

**Comment by rafaeln** [comment]
Easier than I could have thought. Thanks for pointing the path out. You changed the option names you had originally documented on the readme, though. Whereas the readme gives the following line `cm-rgb-monitor --cpu-color=#FFA500 --bg-color=#00FFFF --show-sensor --low-color=#00FF00 --high-color=#FF0000`, now the option name is `---show-temp` and `--temp-low-color` and `--temp-high-color`, so that the command that actually runs is `/cm-rgb-monitor --cpu-color=#FFA500 --bg-color=#00FFFF --show-temp --temp-low-color=#00FF00 --temp-high-color=#FF0000`

**Comment by gfduszynski** [comment]
You are right, I was hesitant to update the readme before I have build published as most people install from pip and wont have this function yet.

I'm planning to refactor readme tomorrow and then release.

In the mean time I've added rainbow and cycle support for the ring if you are interested :)
I've also set default interval for cm-rgb-monitor to 0.2 as this does not flicker in my opinion.
Could you try this interval and give me your opinion ?

**Comment by rafaeln** [comment]
I've pulled the newest commit and I'm running `cm-rgb-monitor` right now. Yes, I do notice less flickering, but now the AMD logo is a blinking light red. CPU temperature is being shown by the fan itself, right?

**Comment by rafaeln** [comment]
Oh, and I'm glad the rainbow is back. I couldn't restore it through a Win10 VM and had already come to terms with the fact that I would never see it again.

**Comment by gfduszynski** [comment]
I've added wiki page https://github.com/gfduszynski/cm-rgb/wiki/Installation-&-Configuration
