### ISSUE TITLE
Mirage support

### ISSUE THREAD

**Issue by jjriggs** [gfduszynski/cm-rgb#28]
Hello!

Do you plan on adding mirage support? I'd like to write a script that continuously polls the CPU fan speed through PySensors, then updates the LED frequency to maintain the same visual illusion.

Thanks,
Jordan

**Comment by gfduszynski** [comment]
Hi :)
The cooler has support for mirage in firmware, script won't be necessary.
However I no longer have access to windows and it may take some time for me
to record the communication. Maybe you have dual boot setup ?

**Comment by jjriggs** [comment]
Hi,

I do have a dual boot setup. If you can tell me how, I'd be happy to sniff the USB messages between the Cooler Master tool and the fan when adjusting the LED frequency.

Jordan

**Comment by gfduszynski** [comment]
You can try this tool https://freeusbanalyzer.com/ (or any other usb analyzing software)

For the purpose of recording its best to turn off everything besides fan backlight, this will reduce the number of packets that have to be analyzed.

Following steps are necessary:
1. Apply settings with only fan backlight enabled
2. Start recording usb communication
3. Apply settings with mirage enabled
4. Stop recording and save / export the communication log
5. Start recording again with clear log
6. Apply settings with mirage disabled
7. Stop recording and save / export the communication log

General idea is to find what changes in the messages when mirage is enabled

If I remember correctly mirage has some parameters to set, you would have to try to record the log with different settings so that we can figure out which bytes change.

Good luck :+1:

**Comment by gfduszynski** [comment]
I was going through ctrl.py in cm-rgb and turns out I already looked at mirage.
I have hardcoded packet to disable it
```python
P_MIRAGE_OFF = new_packet.__func__(0, 0x51, 0x71, 0x00, 0x00, 0x01, 0x00, 0xFF, 0x4A, 0x02, 0x00, 0xFF, 0x4A, 0x03,
                                       0x00, 0xFF, 0x4A, 0x04, 0x00, 0xFF, 0x4A)
```

Packet that enables it should look roughly similar.

**Comment by jjriggs** [comment]
Hello again,

I'm no USB expert, so I was stumbling in the dark. But I've attached what I _think_ are the relevant packets from the USB exchange. I captured the first host->device packet in the stream, which also matched the OFF packet you posted. I matched them with screencaps of the after-action state of the Cooler Master GUI. In other words, I performed the action in the UI, recorded the packet, then screen capped the GUI.

Hope this is helpful!

[mirage_packets.zip](https://github.com/gfduszynski/cm-rgb/files/4688798/mirage_packets.zip)

**Comment by gfduszynski** [comment]
That reminds me of when I started this :) great work!
This should be sufficient.

**Comment by mpsdskd** [comment]
Idle weekend went searches turned up the following repo:
https://github.com/serebit/wraith-master

This software already seems to implement mirage effect, so adapting code might be easier than fully reverse engineering.

Here is the code for setting the frequency:

https://github.com/serebit/wraith-master/blob/master/core/src/linuxX64Main/kotlin/prism/WraithPrism.kt

**Comment by gfduszynski** [comment]
I'll get to it then :+1:

**Comment by gfduszynski** [comment]
Mirage support is available in master.
Thank you guys :1st_place_medal:
