### ISSUE TITLE
Show CPU frequency using logo color

### ISSUE THREAD

**Issue by mpsdskd** [gfduszynski/cm-rgb#32]
I wasn't sure whether just showing the CPU usage & temperature was nerdy enough....

So I programmed it to also show the CPU frequency with the logo color.

It periodically reads all frequency data from /sys/devices/system/cpu/cpu{i}/cpufreq/scaling_cur_freq.
https://github.com/mpsdskd/cm-rgb/blob/master/scripts/cm-rgb-monitor

What I do not know yet: 
- Is the sysfs path the same for all OSs?
- I'm using the same colors for the logo as for the fan - configurable?
- Didn't test for performance, might be possible more efficiently.

**Comment by gfduszynski** [comment]
I think it's not nerdy enough and frequency info will be a great addition 👍 

1) For the readout I think you could try to use https://pypi.org/project/psutil/ since we 
already use it in cm-rgb-monitor.

```python
>>> psutil.cpu_freq()
scpufreq(current=931.42925, min=800.0, max=3500.0)
```

2) I think it would be best to give the user ability to set the desired color optionally.
3) Hard to tell right now, but I've run a test on my nas with:
```
watch -n.1 "cat /proc/cpuinfo | grep \"^[c]pu MHz\""
```
Frequency is all over the place so perhaps this should not be updated on every loop iteration, but instead averaged for 1s window.

**Comment by mpsdskd** [comment]
1. Looks good, I didn't know that library. With this library, also the temperatures can be read, it's probably possible to get rid of the pysensor library requirement.
2. Yeah, why not.
3. Yes it jumps around a bit. Perhaps something like 
```
new_freq_value = n*current_freq_value+(1-n)*last_freq_value
```
with n=0.1 should smooth it out. That is the simplest low-pass filter possible. Filter value could be set by user also.

**Comment by gfduszynski** [comment]
1). Sounds great, actually the sensors api looks better in psutil
3). I like this, it's simple yet should be effective. Will you try this ?

**Comment by mpsdskd** [comment]
https://github.com/gfduszynski/cm-rgb/pull/33

Please test.
- Why iterating over all frequency values? -> I want the logo to change color also on single core boost.
- Smoothing is a float from 0 (no smoothing) to 1 (value does not change at all) and seems to work nicely.

**Comment by gfduszynski** [comment]
All looks good :+1: 
Thank you for this awesome addition!
