### ISSUE TITLE
failed to disable all rgb

### ISSUE THREAD

**Issue by eskuai** [gfduszynski/cm-rgb#64]
Hello,

Using cm-rgb on Fedora, dnf install mode ...

Trying to disable all rgb , I get:

 ```
Command ran: cm-rgb-cli set logo --mode=static --color=#000000 --brightness=0 --speed=0 fan --mode=static --color=#000000 --brightness=0 --speed=0 ring --mode=static --color=#ffffff --brightness=0 --speed=0 save
Traceback (most recent call last):
  File "/usr/bin/cm-rgb-cli", line 23, in <module>
    @setup_group.resultcallback()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?
```

How can i disable all rgb?

Tx

**Comment by gfduszynski** [comment]
Hi!
I have not been keeping up with the project for quite some time, however the issue is caused by newer version of 'Click' dependency.

In any case, I suppose it might just be enough to edit ``/usr/bin/cm-rgb-cli``
and replace ``resultcallback`` with ``result_callback``.

Other option would be to downgrade click to 7.x.x which should work as well.

Good luck!

**Comment by eskuai** [comment]
Hello!

I've replaced the file, with your comments, and it is ok, but I got a lot of new errors....

Tx
