### ISSUE TITLE
Support for RGB header pins on motherboard

### ISSUE THREAD

**Issue by regulator-g** [gfduszynski/cm-rgb#8]
Hi
I have this program installed and get the error Exception: No devices found
My Prism is plugged into the RGB header pins on motherboard I'm guessing this program only works if the Prism is plugged into the USB pins? are you likely to support RGB pins in future or is that a lot more complicated?

**Comment by gfduszynski** [comment]
Hi,
As far as I know with RGB header connected you can only control fan color.
This a limitation of the controller firmware.

It would be difficult for me to pursue support of RGB header due to 
the fact that implementation would wildly vary form motherboard to another.
Every manufacturer has different incompatible type of software to manage RGB.

There are project's out there that try to follow this direction however:
https://gitlab.com/CalcProgrammer1/OpenRGB

Hope this helps.
